In [1]:
import numpy as np

In [2]:
import pandas as p

In [3]:
mohan=np.random.randint(2,25,5)

In [4]:
mohan

array([10,  5, 21, 21,  2])

In [5]:
type(mohan)

numpy.ndarray

In [6]:
mohan.shape

(5,)

In [7]:
mohan2d=np.array([[1,2,3],[4,5,6]])

In [8]:
mohan2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
mohan2d.shape

(2, 3)

In [10]:
mohan2d[0]

array([1, 2, 3])

In [11]:
mohan2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],np.float32)

In [16]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.], dtype=float32)

In [21]:
a.reshape(4,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [22]:
a2=a


In [23]:
a2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.], dtype=float32)

In [24]:
a2.reshape(4,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [25]:
a2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.], dtype=float32)

In [26]:
np.add(a,a2)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32.], dtype=float32)

In [27]:
ab=a.reshape(4,4)

In [29]:
np.subtract(a,a2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [30]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.divide(a,a2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

In [32]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[10],[20]])

In [33]:
np.add(c,d)

array([[11, 12, 13],
       [24, 25, 26]])

In [34]:
a-a2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)